# Generated by Django 6.1.1 on 2026-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada para Compras'), ('EM_ANALISE', 'Em Análise'), ('DEVOLVIDA', 'Devolvida'), ('EM_CORRECAO', 'Em Correção'), ('FINALIZADA', 'Finalizada')], db_index=True, default='RASCUNHO', max_length=30),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='motivo',
            field=models.CharField(choices=[('EVIDENCIA_INSUFICIENTE', 'Evidência insuficiente'), ('DOCUMENTO_INVALIDO', 'Documento inválido'), ('JUSTIFICATIVA_INSUFICIENTE', 'Justificativa insuficiente'), ('INFORMACAO_INCOMPLETA', 'Informação incompleta'), ('RESPOSTA_INCORRETA', 'Resposta incorreta'), ('OUTRO', 'Outro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não'), ('NA', 'Não se aplica')], max_length=30),
        ),
    ]
