# Generated by Django 6.1.1 on 2026-09-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='ajuda',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='questao',
            name='critica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questao',
            name='uso_interno_compras',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('SIM_NAO', 'Sim ou Nao'), ('TEXTO', 'Texto'), ('MULTIPLA_ESCOLHA', 'Multipla escolha'), ('ESCALA_0_5', 'Escala de 0 a 5'), ('ARQUIVO', 'Arquivo')], default='SIM_NAO', max_length=30),
        ),
    ]
