# Generated by Django 6.1.1 on 2026-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0002_questao_ajuda_questao_critica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='tipo',
            field=models.CharField(choices=[('SIM_NAO', 'Sim ou Não'), ('TEXTO', 'Texto'), ('MULTIPLA_ESCOLHA', 'Múltipla escolha'), ('ESCALA_0_5', 'Escala de 0 a 5'), ('ARQUIVO', 'Arquivo')], default='SIM_NAO', max_length=30),
        ),
    ]
