# Generated by Django 6.1.1 on 2026-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('AVALIACAO_DISPONIVEL', 'Avaliação disponível'), ('AVALIACAO_DEVOLVIDA', 'Avaliação devolvida'), ('AVALIACAO_APROVADA', 'Avaliação aprovada'), ('VENCIMENTO', 'Vencimento')], max_length=40),
        ),
    ]
