# Generated by Django 6.1.1 on 2026-09-18 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('fornecedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('QUALIFICADO', 'Qualificado'), ('RESSALVAS', 'Qualificado com Ressalvas'), ('NAO_QUALIFICADO', 'Nao Qualificado'), ('INDEFINIDO', 'Indefinido')], max_length=30)),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inicio_vigencia', models.DateField()),
                ('fim_vigencia', models.DateField()),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacao_registro', to='avaliacoes.avaliacao')),
                ('definida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualificacoes', to='fornecedores.fornecedor')),
            ],
            options={
                'ordering': ['-fim_vigencia'],
                'indexes': [models.Index(fields=['status'], name='qualificaco_status_fe9561_idx'), models.Index(fields=['fim_vigencia'], name='qualificaco_fim_vig_ea0882_idx')],
            },
        ),
    ]
