# Generated by Django 6.1.1 on 2026-09-18 19:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('SIM_NAO', 'Sim ou Nao'), ('TEXTO', 'Texto'), ('MULTIPLA_ESCOLHA', 'Multipla escolha')], default='SIM_NAO', max_length=30)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('peso', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('obrigatoria', models.BooleanField(default=True)),
                ('exige_evidencia_se_sim', models.BooleanField(default=True)),
                ('exige_justificativa_se_nao', models.BooleanField(default=True)),
                ('ativa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='questionarios.categoria')),
            ],
            options={
                'ordering': ['categoria__ordem', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='OpcaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rotulo', models.CharField(max_length=80)),
                ('valor', models.CharField(max_length=80)),
                ('pontuacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativa', models.BooleanField(default=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opcoes', to='questionarios.questao')),
            ],
            options={
                'ordering': ['ordem', 'rotulo'],
            },
        ),
        migrations.CreateModel(
            name='QuestionarioVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=160)),
                ('publicado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes', to='questionarios.questionario')),
            ],
            options={
                'ordering': ['questionario', '-numero'],
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='versao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='questionarios.questionarioversao'),
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['ativa'], name='questionari_ativa_4b04ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='opcaoresposta',
            constraint=models.UniqueConstraint(fields=('questao', 'valor'), name='uniq_opcao_por_questao'),
        ),
        migrations.AddConstraint(
            model_name='questionarioversao',
            constraint=models.UniqueConstraint(fields=('questionario', 'numero'), name='uniq_questionario_versao'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('versao', 'nome'), name='uniq_categoria_por_versao'),
        ),
    ]
