# Generated by Django 6.1.1 on 2026-09-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cargo_responsavel',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='quantidade_funcionarios',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
