# Generated by Django 6.1.1 on 2026-09-18 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('AVALIACAO_DISPONIVEL', 'Avaliacao disponivel'), ('AVALIACAO_DEVOLVIDA', 'Avaliacao devolvida'), ('AVALIACAO_APROVADA', 'Avaliacao aprovada'), ('VENCIMENTO', 'Vencimento')], max_length=40)),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.TextField()),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tipo', 'lida_em'], name='notificacoe_tipo_217f8c_idx')],
            },
        ),
    ]
