# Generated by Django 6.1.1 on 2026-09-18 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('razao_social', models.CharField(max_length=180)),
                ('nome_fantasia', models.CharField(blank=True, max_length=180)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('codigo_externo', models.CharField(blank=True, db_index=True, max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('BLOQUEADO', 'Bloqueado')], default='ATIVO', max_length=20)),
                ('qualificacao_atual', models.CharField(blank=True, max_length=40)),
                ('pontuacao_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('validade_qualificacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['status'], name='fornecedore_status_8cb071_idx'), models.Index(fields=['validade_qualificacao'], name='fornecedore_validad_dd8ac9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FornecedorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='fornecedores.fornecedor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedor_vinculo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fornecedor', 'user'), name='uniq_fornecedor_usuario')],
            },
        ),
    ]
