# Generated by Django 6.1.1 on 2026-09-18 19:19

import apps.avaliacoes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
        ('questionarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('periodo', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADA', 'Enviada para Compras'), ('EM_ANALISE', 'Em Analise'), ('DEVOLVIDA', 'Devolvida'), ('EM_CORRECAO', 'Em Correcao'), ('FINALIZADA', 'Finalizada')], db_index=True, default='RASCUNHO', max_length=30)),
                ('pontuacao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('qualificacao', models.CharField(blank=True, max_length=40)),
                ('inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fim_vigencia', models.DateField(blank=True, null=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='fornecedores.fornecedor')),
                ('questionario_versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='questionarios.questionarioversao')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(choices=[('EVIDENCIA_INSUFICIENTE', 'Evidencia insuficiente'), ('DOCUMENTO_INVALIDO', 'Documento invalido'), ('JUSTIFICATIVA_INSUFICIENTE', 'Justificativa insuficiente'), ('INFORMACAO_INCOMPLETA', 'Informacao incompleta'), ('RESPOSTA_INCORRETA', 'Resposta incorreta'), ('OUTRO', 'Outro')], max_length=40)),
                ('comentario', models.TextField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='avaliacoes.avaliacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devolucoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status_origem', models.CharField(blank=True, max_length=30)),
                ('status_destino', models.CharField(max_length=30)),
                ('acao', models.CharField(max_length=80)),
                ('comentario', models.TextField(blank=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='avaliacoes.avaliacao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('resposta', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Nao'), ('NA', 'Nao se aplica')], max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('justificativa', models.TextField(blank=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacoes.avaliacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='questionarios.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('arquivo', models.FileField(upload_to=apps.avaliacoes.models.evidencia_upload_to)),
                ('nome_original', models.CharField(max_length=255)),
                ('extensao', models.CharField(max_length=12)),
                ('mime_type', models.CharField(max_length=120)),
                ('tamanho', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidencias', to=settings.AUTH_USER_MODEL)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='avaliacoes.resposta')),
            ],
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['status'], name='avaliacoes__status_914217_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['fornecedor', 'status'], name='avaliacoes__fornece_9cd151_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['fim_vigencia'], name='avaliacoes__fim_vig_184450_idx'),
        ),
        migrations.AddConstraint(
            model_name='resposta',
            constraint=models.UniqueConstraint(fields=('avaliacao', 'questao'), name='uniq_resposta_avaliacao_questao'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['ativo'], name='avaliacoes__ativo_4b7c89_idx'),
        ),
    ]
