# Generated by Django 6.1.1 on 2026-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificacao',
            name='status',
            field=models.CharField(choices=[('QUALIFICADO', 'Qualificado'), ('RESSALVAS', 'Qualificado com Ressalvas'), ('NAO_QUALIFICADO', 'Não Qualificado'), ('INDEFINIDO', 'Indefinido')], max_length=30),
        ),
    ]
